import { useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronLeft, ChevronRight, Menu, X, Plus, Heart, Sun, Layers, Truck, Sparkles } from 'lucide-react'
import { models, imagePath } from './models'
import { businessPhotos } from './business-models'
import { extraPhotos } from './more-models'
import { MotionPreferences, VisualAtmosphere } from './VisualEffects'
import { ReadingProgress, usePageMotion, WordReveal } from './Motion'
import { WhatsAppButton } from './Effects'
import { whatsapp, cnpj } from './brand'

const photos=[...models,...extraPhotos,...businessPhotos]
function Photo({name,eager=false,...props}){
 const item=photos.find(p=>p.image===name)
 return <img src={imagePath(item)} srcSet={`${imagePath(item,true)} 480w, ${imagePath(item)} 1200w`} sizes="(max-width:700px) 100vw, 60vw" alt={item.alt} loading={eager?'eager':'lazy'} decoding="async" {...props}/>
}
const sectionOrders={construction:['services','tool','about','gallery'],solar:['tool','about','services','gallery'],hotel:['gallery','tool','about','services'],events:['about','gallery','tool','services'],technology:['tool','services','about','gallery'],logistics:['services','tool','gallery','about'],fashion:['tool','gallery','about','services'],cleaning:['tool','services','about','gallery']}
const labels={construction:'Seu projeto',solar:'Aplicações',hotel:'Sua estadia',events:'Seu evento',technology:'Conexões',logistics:'Acompanhar',fashion:'Coleção',cleaning:'Seu espaço'}
const n=i=>String(i+1).padStart(2,'0')
function Head({label,children,text}){return <div className="biz-heading reveal"><div><span className="biz-kicker">{label}</span><h2>{children}</h2></div>{text&&<p>{text}</p>}</div>}
function Picks({items,active,setActive,label}){return <div className="biz-picks" role="group" aria-label={label}>{items.map((item,i)=><button key={item} aria-pressed={active===i} onClick={()=>setActive(i)}>{item}</button>)}</div>}
function BusinessExperience({model:m}){
 const [active,setActive]=useState(0),[selected,setSelected]=useState([]),[guests,setGuests]=useState(80)
 const toggle=item=>setSelected(old=>old.includes(item)?old.filter(v=>v!==item):[...old,item])
 const next=<a className="biz-text-link" href="#consulta">Continuar a experiência <ArrowRight size={18}/></a>
 let content
 if(m.theme==='construction')content=<div className="build-planner"><div className="build-stages">{m.steps.map(([t],i)=><button key={t} aria-pressed={active===i} onClick={()=>setActive(i)}><span>{n(i)}</span>{t}<ArrowUpRight size={20}/></button>)}</div><article className="biz-stage"><span className="blueprint-mark" aria-hidden="true"><Layers size={110}/></span><span className="biz-kicker">ETAPA {n(active)} / DO PLANO À ENTREGA</span><h3>{m.steps[active][0]}</h3><p>{m.steps[active][1]}</p><div className="build-bars" aria-hidden="true">{m.steps.map((_,i)=><i key={i} className={i<=active?'is-done':''}/>)}</div>{next}</article></div>
 if(m.theme==='solar')content=<div className="solar-explorer"><div className="solar-orbit" aria-hidden="true"><Sun size={100}/><span>Uma fonte.<br/><strong>Novos caminhos.</strong></span></div><div><Picks items={['Casa','Empresa','Campo']} active={active} setActive={setActive} label="Aplicação de energia solar"/><article className="biz-stage"><span className="biz-kicker">UM ESTUDO PARA CADA CENÁRIO</span><h3>{m.services[active][0]}</h3><p>{m.services[active][1]}</p><ul>{[['Rotina de consumo','Condições da cobertura','Área disponível'],['Perfil da operação','Consumo ao longo do dia','Condições da unidade'],['Necessidades da propriedade','Área para implantação','Características da instalação']][active].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul>{next}</article></div></div>
 if(m.theme==='hotel')content=<div className="hotel-rooms"><Photo name={['suite','hotel','arquitetura'][active]}/><div className="biz-stage"><span className="biz-kicker">O SEU REFÚGIO / {n(active)}</span><Picks items={m.services.map(s=>s[0])} active={active} setActive={setActive} label="Escolher acomodação"/><h3>{m.services[active][0]}</h3><p>{m.services[active][1]}</p><div className="room-details"><span>{['Um tempo a dois','Dias mais leves','Histórias em família'][active]}</span><span>Conceito ilustrativo</span></div><a className="biz-button" href="#consulta">Imaginar minha estadia <ArrowUpRight size={18}/></a></div></div>
 if(m.theme==='events')content=<div className={'event-mood event-mood-'+active}><div className="event-mood-poster"><span>UM ENCONTRO.</span><strong>{['natural.','clássico.','vibrante.'][active]}</strong><div className="event-swatches" aria-hidden="true">{[['#8b9678','#d4c6a8','#e7e4d9'],['#3a2444','#bc9c64','#efe8e0'],['#ef613d','#dbe852','#ca96ed']][active].map(c=><i key={c} style={{background:c}}/>)}</div><small>PAINEL DE INTENÇÃO / CELEBRA</small></div><div className="biz-stage"><Picks items={['Natural','Clássico','Vibrante']} active={active} setActive={setActive} label="Estilo do evento"/><h3>{['Leveza que aproxima.','Elegância que acolhe.','Energia para celebrar.'][active]}</h3><p>{['Tons suaves, materiais naturais e uma atmosfera de encontro.','Uma composição com contrastes delicados e detalhes marcantes.','Cor, movimento e referências que dão personalidade ao momento.'][active]}</p><label className="biz-range">Público imaginado: <strong>{guests} convidados</strong><input type="range" min="20" max="300" step="10" value={guests} onChange={e=>setGuests(Number(e.target.value))}/></label><p className="biz-small" role="status">Referência: estilo {['natural','clássico','vibrante'][active]}, para {guests} pessoas.</p>{next}</div></div>
 if(m.theme==='technology')content=<div className="tech-flow"><div><span className="biz-kicker">ESCOLHA O QUE CONECTAR</span><div className="biz-checks">{['Atendimento','Vendas','Operação','Gestão'].map(t=><button key={t} aria-pressed={selected.includes(t)} onClick={()=>toggle(t)}>{selected.includes(t)?<Check size={18}/>:<Plus size={18}/>} {t}</button>)}</div><p className="biz-small">Interação ilustrativa. Nenhum sistema externo é conectado.</p></div><div className="biz-stage tech-system"><div className="tech-node">nexo_<span>CAMADA DE INTEGRAÇÃO</span></div><div className="tech-connections" role="status">{selected.length?selected.map(t=><span key={t}><i/>{t}<Check size={14}/></span>):<p>Escolha ao lado as áreas do seu fluxo.</p>}</div><p>Informações organizadas para que as etapas conversem entre si.</p>{next}</div></div>
 if(m.theme==='logistics')content=<div className="logistics-track"><div className="track-label"><Truck size={35}/><span>ROTA DEMONSTRATIVA<strong>ORIGEM → DESTINO</strong></span></div><div className="track-line">{['Solicitação','Planejamento','Em movimento','Concluída'].map((t,i)=><button key={t} aria-pressed={active===i} className={i<=active?'passed':''} onClick={()=>setActive(i)}><span>{i<active?<Check size={18}/>:n(i)}</span><strong>{t}</strong></button>)}</div><article className="biz-stage track-status" aria-live="polite"><span className="biz-kicker">ETAPA SELECIONADA / {n(active)}</span><h3>{m.steps[active][0]}</h3><p>{m.steps[active][1]}</p><div className="track-controls"><button aria-label="Etapa anterior" onClick={()=>setActive(v=>Math.max(0,v-1))} disabled={active===0}><ChevronLeft/></button><span>{n(active)} / 04</span><button aria-label="Próxima etapa" onClick={()=>setActive(v=>Math.min(3,v+1))} disabled={active===3}><ChevronRight/></button></div></article></div>
 if(m.theme==='fashion')content=<div className="fashion-collection"><Picks items={['Tudo','Essenciais','Texturas']} active={active} setActive={setActive} label="Filtrar coleção"/><div className="fashion-products">{[{name:'Formas do cotidiano',type:1,image:'moda'},{name:'Detalhes com presença',type:2,image:'boutique'},{name:'Expressão pessoal',type:1,image:'retrato'}].filter(p=>!active||p.type===active).map(p=><article key={p.name}><Photo name={p.image}/><div><h3>{p.name}</h3><button aria-label={(selected.includes(p.name)?'Remover':'Salvar')+' '+p.name} aria-pressed={selected.includes(p.name)} onClick={()=>toggle(p.name)}><Heart fill={selected.includes(p.name)?'currentColor':'none'} size={20}/></button></div><small>REFERÊNCIA DE COLEÇÃO · SEM VENDA</small></article>)}</div><p role="status" className="biz-small">{selected.length?`${selected.length} referências salvas nesta visita.`:'Salve as referências que combinam com você.'}</p></div>
 if(m.theme==='cleaning')content=<div className="cleaning-planner"><div><div className="cleaning-symbol" aria-hidden="true"><Sparkles size={64}/></div><h3>Um cuidado para cada canto.</h3><div className="biz-checks">{['Sala','Cozinha','Banheiros','Quartos','Escritório','Área externa'].map(t=><button key={t} aria-pressed={selected.includes(t)} onClick={()=>toggle(t)}>{selected.includes(t)?<Check size={18}/>:<Plus size={18}/>} {t}</button>)}</div></div><div className="biz-stage cleaning-receipt"><span className="biz-kicker">SEU ESBOÇO DE SOLICITAÇÃO</span><h3>Vamos cuidar<br/>do seu espaço.</h3><div role="status">{selected.length?selected.map(t=><p key={t}><Check size={17}/>{t}</p>):<p>Selecione os ambientes para visualizar suas prioridades.</p>}</div><span className="biz-small">O escopo final depende da avaliação do local.</span>{next}</div></div>
 return <section className="biz-section biz-experience" id="experiencia"><div className="biz-container"><Head label="EXPLORE A EXPERIÊNCIA" text={m.toolText}>{m.toolTitle}</Head>{content}</div></section>
}
export default function BusinessDemo({model:m}){
 const ref=useRef(null);usePageMotion(ref)
 const [menu,setMenu]=useState(false),[result,setResult]=useState('')
 const nav=[['#experiencia',labels[m.theme]],['#solucoes','Soluções'],['#sobre','Sobre'],['#inspiracoes','Inspirações'],['#duvidas','Dúvidas']]
 const services=<section id="solucoes" className="biz-section biz-container"><Head label="O QUE PODEMOS FAZER" text="Conheça as possibilidades e escolha o que faz sentido para seu momento.">{m.theme==='hotel'?'Dias para viver do seu jeito.':m.theme==='fashion'?'Uma coleção, muitas possibilidades.':'Soluções que começam pela sua necessidade.'}</Head><div className="biz-services">{m.services.map(([t,p],i)=><article className="reveal" key={t}><span className="biz-index">{n(i)}</span><h3>{t}</h3><p>{p}</p><a href="#consulta">Quero conhecer <ArrowUpRight size={18}/></a></article>)}</div></section>
 const about=<section className="biz-section biz-about" id="sobre"><div className="biz-container biz-about-grid"><div className="biz-about-photo"><Photo name={m.gallery[1]}/><span>{m.detail}</span></div><div className="reveal"><span className="biz-kicker">O QUE NOS MOVE</span><h2>{m.aboutTitle}</h2><p>{m.about}</p><p>Uma relação próxima começa com expectativas alinhadas, informações claras e atenção ao que torna cada projeto diferente.</p><a href="#caminho" className="biz-text-link">Conheça nosso caminho <ArrowRight size={18}/></a></div></div></section>
 const gallery=<section className="biz-section biz-container" id="inspiracoes"><Head label="UM OLHAR MAIS DE PERTO" text="Fotografias ilustrativas para explorar a atmosfera deste projeto conceitual.">{m.galleryTitle}</Head><div className="biz-gallery">{m.gallery.map((name,i)=><figure className="reveal" key={name}><Photo name={name}/><figcaption><span>{n(i)} / {m.galleryLabels[i]}</span><ArrowUpRight size={22}/></figcaption></figure>)}</div></section>
 return <div ref={ref} className={'business-demo biz-'+m.theme} id="inicio"><ReadingProgress/><MotionPreferences/><a className="skip-link" href="#business-main">Pular para o conteúdo</a><div className="biz-demo-bar"><a href="/#modelos"><ArrowLeft size={15}/> Todos os modelos</a><span>Marca fictícia · {m.profession}</span><a href={whatsapp(`Olá! Quero um orçamento de site inspirado no modelo ${m.name}.`)} target="_blank" rel="noopener noreferrer">Quero um site assim <ArrowUpRight size={15}/></a></div><header className="biz-header biz-container"><a className="biz-brand" href="#inicio">{m.brand}<span>®</span></a><nav aria-label="Navegação do modelo">{nav.map(([h,t])=><a href={h} key={h}>{t}</a>)}</nav><a className="biz-header-action" href="#consulta">Vamos conversar <ArrowUpRight size={17}/></a><button className="biz-menu-toggle" aria-label={menu?'Fechar menu':'Abrir menu'} aria-expanded={menu} aria-controls="biz-mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>{menu&&<nav className="biz-mobile" id="biz-mobile" aria-label="Menu no celular">{[...nav,['#consulta','Vamos conversar']].map(([h,t])=><a href={h} key={h} onClick={()=>setMenu(false)}>{t}<ArrowUpRight size={17}/></a>)}</nav>}</header><main id="business-main">
 <section className="biz-hero"><VisualAtmosphere theme={m.effect}/><div className="biz-container biz-hero-grid"><div className="biz-hero-copy"><span className="biz-kicker">{m.kicker}</span><h1><WordReveal text={m.headline}/></h1><p>{m.description}</p><div className="biz-hero-actions"><a className="biz-button" href="#solucoes">{m.cta}<ArrowUpRight size={18}/></a><a href="#experiencia" className="biz-text-link">{labels[m.theme]}<ArrowRight size={17}/></a></div><span className="biz-hero-note">{m.detail}</span></div><div className="biz-hero-photo"><Photo name={m.image} eager/><span className="biz-photo-caption"><b>{m.brand}</b><span>{m.profession}</span></span>{m.theme==='solar'&&<span className="solar-badge"><Sun size={27}/> O futuro começa<br/>com uma escolha.</span>}{m.theme==='technology'&&<span className="tech-badge"><i/> Ideias conectadas.<br/><strong>Operações mais simples.</strong></span>}</div></div></section>
 <div className="biz-ribbon"><div className="biz-container">{m.features.map(t=><span key={t}><Check size={17}/>{t}</span>)}</div></div>
 {sectionOrders[m.theme].map(key=><div key={key}>{({services,about,gallery,tool:<BusinessExperience model={m}/>})[key]}</div>)}
 <section className="biz-section biz-manifesto"><div className="biz-container"><span className="biz-kicker">NOSSO JEITO DE FAZER</span><h2>{m.detail}</h2><div className="biz-principles">{m.features.map((t,i)=><article className="reveal" key={t}><span>{n(i)}</span><h3>{t}</h3><p>{m.steps[i][1]}</p></article>)}</div></div></section>
 <section className="biz-section biz-container" id="caminho"><Head label="DO PRIMEIRO CONTATO AOS PRÓXIMOS PASSOS">Um caminho claro para começar.</Head><div className="biz-journey">{m.steps.map(([t,p],i)=><article className="reveal" key={t}><span>{n(i)}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
 <section className="biz-editorial biz-container"><div><span className="biz-kicker">UMA IDEIA PARA LEVAR</span><h2>{m.editorial[0]}</h2><p>{m.editorial[1]}</p><a className="biz-text-link" href="#consulta">Vamos conversar sobre isso <ArrowUpRight size={17}/></a></div><Photo name={m.gallery[2]}/></section>
 <section className="biz-section biz-container biz-faq" id="duvidas"><div><span className="biz-kicker">ANTES DO PRIMEIRO CONTATO</span><h2>Suas perguntas<br/>têm espaço aqui.</h2></div><div>{[[m.question,m.answer],['Como funciona o primeiro contato?',m.steps[0][1]+' Depois, alinhamos as condições e os próximos passos.'],['Onde consulto valores e disponibilidade?','Uma proposta real depende do contexto e do escopo. Esta página é uma demonstração, sem preços, produtos ou agenda reais.'],['Este site pertence a uma empresa real?','Não. A marca é fictícia e as fotografias são ilustrativas. Este projeto demonstra uma possibilidade de site profissional criado pela Soluções Digitais.'],['Posso ter um site assim para minha empresa?','Sim. Use o WhatsApp para solicitar uma proposta com a identidade, os conteúdos e as funcionalidades do seu negócio.']].map(([q,a])=><details key={q}><summary>{q}<Plus size={17}/></summary><p>{a}</p></details>)}</div></section>
 <section className="biz-section biz-consult" id="consulta"><div className="biz-container biz-consult-grid"><div><span className="biz-kicker">O SEU PRÓXIMO PASSO</span><h2>{m.contactTitle}</h2><p>Experimente como seu cliente pode encontrar o caminho até uma primeira conversa.</p><aside><Sparkles size={23}/><span><strong>Demonstração interativa.</strong> Este formulário não coleta dados pessoais, não envia mensagens e não realiza contratações.</span></aside></div><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);setResult(`Interesse em ${data.get('interesse')}. Preferência: ${data.get('momento')}. Esta é uma simulação: nenhum pedido foi enviado.`)}}><span className="biz-kicker">EXPERIMENTE O PRIMEIRO CONTATO</span><h3>O que você tem em mente?</h3><label>Seu interesse<select name="interesse">{m.services.map(([t])=><option key={t}>{t}</option>)}</select></label><label>Como gostaria de começar?<select name="momento"><option>Conhecer as possibilidades</option><option>Conversar sobre um projeto</option><option>Entender o atendimento</option></select></label><button className="biz-button" type="submit">Simular meu interesse <ArrowUpRight size={18}/></button>{result&&<p className="biz-result" role="status">{result}</p>}</form></div></section>
 <section className="biz-section biz-container biz-conversion"><span className="biz-kicker">AGORA, IMAGINE A SUA MARCA AQUI</span><h2>Seu negócio merece<br/>ser apresentado assim.</h2><p>Gostou deste caminho? Vamos criar um site com a identidade da sua empresa, conteúdo pensado para seu público e um caminho claro para solicitar orçamento.</p><a className="biz-button" href={whatsapp(`Olá! Gostei do modelo ${m.name}, para ${m.profession.toLowerCase()}. Quero uma proposta para criar meu site.`)} target="_blank" rel="noopener noreferrer">Quero uma proposta para meu site <ArrowUpRight size={19}/></a><small>Orçamento sem compromisso · Escopo, prazo e investimento alinhados antes de começar.</small></section>
 </main><footer className="biz-footer biz-container"><a className="biz-brand" href="#inicio">{m.brand}</a><p>Marca fictícia · Fotografias ilustrativas<br/>Modelo criado pela <a href="/">Soluções Digitais</a><br/>CNPJ {cnpj}</p><a href="/#modelos">Explorar outros modelos <ArrowUpRight size={17}/></a></footer><WhatsAppButton model={m}/></div>
}
