export const moreModels = [
 {slug:'nutri-viva',brand:'nutri viva',name:'Nutri Viva',category:'Saúde & bem-estar',profession:'Nutricionistas',theme:'nutrition',kicker:'COMIDA DE VERDADE. CUIDADO DE VERDADE.',headline:'Uma relação mais leve com a alimentação.',description:'Escuta, rotina e escolhas possíveis. Um cuidado nutricional que respeita a sua história e o seu momento.',image:'nutricao',photo:'1490645935967-10de6ba17061',alt:'Alimentos frescos e coloridos sobre uma mesa',tags:['Natural','Nutrição','Acolhedor'],cta:'Conheça os acompanhamentos',services:[['Consulta individual','Uma conversa sobre sua rotina, seus objetivos e suas preferências.'],['Acompanhamento','Encontros para rever caminhos e adaptar o planejamento.'],['Educação alimentar','Informação acessível para escolhas com mais autonomia.']],detail:'Cuidar da alimentação também é cuidar da sua rotina.',about:'Acreditamos em uma escuta que vem antes de qualquer planejamento. Conhecer seus hábitos, preferências e desafios é o primeiro passo para construir uma experiência de cuidado próxima e possível.'},
 {slug:'barbearia-distrito',brand:'DISTRITO 62',name:'Barbearia Distrito 62',category:'Negócios',profession:'Barbeiros',theme:'barber',kicker:'ESTILO SEM MEIO-TERMO',headline:'Seu estilo. Nossa assinatura.',description:'Corte, barba e um tempo só seu. Tradição e atitude em um espaço feito para você se sentir em casa.',image:'barbearia',photo:'1503951914875-452162b0f3f1',alt:'Ambiente de barbearia com cadeiras e espelhos',tags:['Urbano','Clássico','Atitude'],cta:'Conheça os serviços',services:[['Corte na medida','Um acabamento pensado para seu estilo e sua rotina.'],['Barba e cuidado','Desenho, alinhamento e atenção aos detalhes.'],['Experiência completa','Corte e barba em um encontro com o seu melhor visual.']],detail:'Não é só sentar na cadeira. É se sentir no seu lugar.',about:'Um espaço de boas conversas e atenção de verdade. Da escolha do corte ao acabamento, cada etapa é feita com tempo e cuidado para respeitar a sua identidade.'},
 {slug:'torque-auto',brand:'TORQUE',name:'Torque Auto Center',category:'Negócios',profession:'Oficinas e serviços automotivos',theme:'automotive',kicker:'CONFIANÇA EM CADA QUILÔMETRO',headline:'Seu carro em boas mãos. Você no caminho certo.',description:'Diagnóstico claro, atenção ao seu veículo e uma conversa sem complicação. Cuidado automotivo do começo ao fim.',image:'oficina',photo:'1486262715619-67b85e0b08d3',alt:'Profissional realizando manutenção em um veículo',tags:['Técnico','Direto','Serviços'],cta:'Encontre o serviço ideal',services:[['Revisão preventiva','Avaliação dos principais sistemas conforme a necessidade do veículo.'],['Diagnóstico','Análise para entender os sinais e orientar os próximos passos.'],['Manutenção','Um planejamento claro dos serviços, com orçamento antes da execução.']],detail:'Você entende o serviço antes de tomar a decisão.',about:'Acreditamos que confiança começa com explicações claras. Por isso, valorizamos o diagnóstico, a comunicação e a organização de cada etapa do atendimento.'},
 {slug:'horizonte-escola',brand:'horizonte.',name:'Horizonte Escola Criativa',category:'Negócios',profession:'Professores e escolas',theme:'education',kicker:'APRENDER ABRE CAMINHOS',headline:'O seu próximo passo começa com uma descoberta.',description:'Aprendizado próximo, projetos na prática e espaço para fazer perguntas. Descubra novas possibilidades para o seu futuro.',image:'educacao',photo:'1503676260728-1c00da094a0b',alt:'Estudantes em um ambiente de aprendizagem',tags:['Colorido','Educação','Comunidade'],cta:'Explore os cursos',services:[['Idiomas','Conversação e situações do dia a dia para aprender com contexto.'],['Tecnologia','Ferramentas e projetos para transformar curiosidade em prática.'],['Criação','Espaço para experimentar, desenvolver ideias e criar com intenção.']],detail:'Conhecimento cresce quando encontra curiosidade.',about:'Cada pessoa aprende de um jeito. Criamos um ambiente de troca, com acompanhamento próximo e atividades que conectam o aprendizado a situações reais.'},
]

export const extraPhotos = [
 {image:'consultorio',photo:'1629909613654-28e377c37b09',alt:'Consultório odontológico com equipamentos modernos'},
 {image:'profissional',photo:'1573497620053-ea5300f94f21',alt:'Profissional em um ambiente de trabalho acolhedor'},
 {image:'escritorio',photo:'1497366754035-f200968a6e72',alt:'Escritório iluminado com espaços de reunião'},
 {image:'reuniao',photo:'1556761175-b413da4baf72',alt:'Equipe reunida para conversar sobre um projeto'},
 {image:'casa',photo:'1600596542815-ffad4c1539a9',alt:'Residência contemporânea com jardim e piscina'},
 {image:'sala',photo:'1600210492486-724fe5c67fb0',alt:'Sala de estar ampla com decoração contemporânea'},
 {image:'salada',photo:'1512621776951-a57141f2eefd',alt:'Prato com vegetais frescos e coloridos'},
 {image:'prato',photo:'1547592180-85f173990554',alt:'Prato gastronômico com ingredientes frescos'},
 {image:'casamento',photo:'1519741497674-611481863552',alt:'Celebração de casamento fotografada em um jardim'},
 {image:'retrato',photo:'1506794778202-cad84cf45f1d',alt:'Retrato de um homem em luz natural'},
 {image:'natureza',photo:'1441974231531-c6227db76b6e',alt:'Luz do sol atravessando uma floresta'},
]
