import { journeys } from './journeys'
import SignatureExperience from './SignatureExperience'
import { usePageMotion, ReadingProgress, WordReveal } from './Motion'
import { cnpj } from './brand'
import { Fragment, useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowUpRight, ArrowRight, Check, Menu, X, Plus, Minus, Sparkles } from 'lucide-react'
import { models, imagePath } from './models'
import { extraPhotos } from './more-models'
import { profiles } from './profiles'
import { whatsapp } from './brand'
import { WhatsAppButton } from './Effects'

const photos = [...models, ...extraPhotos]
function Image({ name, eager = false, ...props }) {
  const item = photos.find(photo => photo.image === name) || models[0]
  return <img src={imagePath(item)} srcSet={`${imagePath(item, true)} 480w, ${imagePath(item)} 1200w`} sizes="(max-width: 700px) 100vw, 60vw" alt={item.alt} loading={eager ? 'eager' : 'lazy'} decoding="async" {...props} />
}
function Heading({ label, children, text }) { return <div className="pro-heading"><div><span className="pro-kicker">{label}</span><h2>{children}</h2></div>{text && <p>{text}</p>}</div> }
const sectionOrder = {"dental":["signature","services","about","gallery"],"law":["about","signature","services","gallery"],"therapy":["signature","about","gallery","services"],"property":["services","signature","gallery","about"],"architecture":["gallery","signature","about","services"],"beauty":["signature","gallery","services","about"],"restaurant":["services","about","signature","gallery"],"fitness":["signature","services","gallery","about"],"pet":["about","signature","gallery","services"],"photography":["gallery","about","signature","services"],"accounting":["signature","about","services","gallery"],"tattoo":["gallery","signature","services","about"],"nutrition":["about","services","signature","gallery"],"barber":["signature","gallery","about","services"],"automotive":["services","signature","about","gallery"],"education":["signature","services","about","gallery"]}
const serviceModes = { property:'catalog', restaurant:'menu', dental:'tabs', therapy:'tabs', nutrition:'tabs', fitness:'tabs', law:'accordion', accounting:'accordion', automotive:'accordion', education:'tabs' }

function ServiceExplorer({ model, profile, onOpen }) {
  const [selected, setSelected] = useState(0)
  const [filter, setFilter] = useState('Todos')
  const services = [...model.services, ...profile.extras]
  const mode = serviceModes[model.theme] || 'cards'
  if (mode === 'catalog') {
    const listings = [ ['Casa Horizonte','Casas','casa','3 quartos · Jardim · Ambientes integrados'], ['Apartamento Vista','Apartamentos','sala','2 quartos · Luz natural · Varanda'], ['Residência Aurora','Casas','imoveis','3 quartos · Área externa · Espaços amplos'], ['Apartamento Essencial','Apartamentos','arquitetura','2 quartos · Sala integrada · Design contemporâneo'] ]
    return <><div className="pro-filters" role="group" aria-label="Filtrar imóveis">{['Todos','Casas','Apartamentos'].map(item => <button key={item} aria-pressed={filter === item} onClick={() => setFilter(item)}>{item}</button>)}</div><p className="pro-muted">Imóveis conceituais · Não são ofertas de venda</p><div className="pro-listings">{listings.filter(item => filter === 'Todos' || item[1] === filter).map(([title,type,image,details]) => <article key={title}><button className="pro-image-button" onClick={() => onOpen({title,image,text:`${details}. Um espaço ilustrativo para demonstrar uma apresentação completa de imóvel, com fotografias, características e chamada para visita. Este imóvel não está à venda.`})} aria-label={`Ver detalhes de ${title}`}><Image name={image}/><span>{type} <ArrowUpRight/></span></button><div><span className="pro-kicker">CURADORIA PRIME URBAN</span><h3>{title}</h3><p>{details}</p><button className="pro-text-button" onClick={() => onOpen({title,image,text:`${details}. Nesta demonstração, você conhece o formato de uma ficha de imóvel. Na versão personalizada, entram as informações reais, a localização e as condições fornecidas pelo corretor.`})}>Conhecer o imóvel <ArrowRight size={18}/></button></div></article>)}</div></>
  }
  if (mode === 'accordion') return <div className="pro-service-accordion">{services.map(([title,text],i) => <article key={title}><h3><button aria-expanded={selected === i} aria-controls={`service-${i}`} onClick={() => setSelected(selected === i ? -1 : i)}><span>0{i+1}</span>{title}{selected === i ? <Minus/> : <Plus/>}</button></h3><div id={`service-${i}`} hidden={selected !== i}><p>{text} O primeiro contato permite compreender sua necessidade e apresentar o escopo do atendimento de forma clara.</p><a href="#demo-contato">Conversar sobre {title.toLowerCase()} <ArrowUpRight size={18}/></a></div></article>)}</div>
  if (mode === 'menu') return <><div className="pro-filters" role="group" aria-label="Categorias do cardápio">{['Para começar','Da cozinha','Para acompanhar'].map((item,i) => <button key={item} aria-pressed={selected === i} onClick={() => setSelected(i)}>{item}</button>)}</div><div className="pro-menu-layout"><Image name={['salada','prato','restaurante'][selected]}/><div><span className="pro-kicker">CARDÁPIO CONCEITUAL</span>{[['Vegetais da estação','Pães & boas conversas','Seleção da casa'],['Da brasa para a mesa','Sabores do dia','Uma escolha para compartilhar'],['Combinações da casa','Pausa para o café','Um final doce']][selected].map((title,i) => <article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{['Ingredientes frescos, texturas e um toque da cozinha.','Uma composição para aproveitar sem pressa.','Detalhes que completam a experiência à mesa.'][i]}</p></div></article>)}<small>Itens ilustrativos. Ingredientes, alergênicos e preços são definidos pelo restaurante na versão final.</small></div></div></>
  if (mode === 'tabs') return <div className="pro-service-explorer"><div className="pro-service-choices" role="group" aria-label="Explorar serviços">{services.map(([title],i) => <button key={title} aria-pressed={selected === i} onClick={() => setSelected(i)}><span>0{i+1}</span>{title}<ArrowUpRight size={19}/></button>)}</div><article className="pro-service-detail" aria-live="polite"><span className="pro-kicker">UMA POSSIBILIDADE PARA VOCÊ</span><h3>{services[selected][0]}</h3><p>{services[selected][1]}</p><p>Conheça a proposta, esclareça suas dúvidas e entenda como essa experiência pode se encaixar na sua rotina. Cada pessoa tem um ponto de partida diferente.</p><ul>{profile.features.map(item => <li key={item}><Check size={17}/>{item}</li>)}</ul><a className="pro-button" href="#demo-contato">Quero saber mais <ArrowUpRight size={18}/></a></article></div>
  return <div className="pro-service-cards">{services.map(([title,text],i) => <article key={title}><span className="pro-service-index">0{i+1}</span><h3>{title}</h3><p>{text}</p><a href="#demo-contato">Explore essa possibilidade <ArrowUpRight size={18}/></a></article>)}</div>
}

function Contact({ model, profile }) {
  const [result,setResult] = useState('')
  const resultRef = useRef(null)
  useEffect(() => { if(result) resultRef.current?.focus() },[result])
  return <section className="pro-contact pro-section" id="demo-contato"><div className="pro-container pro-contact-grid"><div><span className="pro-kicker">O PRÓXIMO PASSO</span><h2>{profile.contactTitle}</h2><p>Conheça o atendimento, compartilhe suas preferências e encontre o melhor caminho para começar.</p><div className="pro-demo-disclosure"><Sparkles size={21}/><p><strong>Este é um site de demonstração.</strong> A marca, os serviços e as imagens são ilustrativos. O formulário apenas simula a experiência: não envia dados nem realiza reservas.</p></div></div><form onSubmit={event => {event.preventDefault();const data=new FormData(event.currentTarget);setResult(`Simulação concluída: interesse em ${data.get('interesse')}, com preferência por ${data.get('periodo')}. Nenhuma solicitação foi enviada e nenhum horário foi reservado.`)}}><span className="pro-kicker">EXPERIMENTE A NAVEGAÇÃO</span><h3>Como podemos receber você?</h3><label>{profile.contactLabel || 'O que você gostaria de conhecer?'}<select name="interesse">{[...model.services,...profile.extras].map(([title]) => <option key={title}>{title}</option>)}</select></label><label>Preferência de período<select name="periodo"><option>Manhã</option><option>Tarde</option><option>A combinar</option></select></label><button className="pro-button" type="submit">Simular solicitação <ArrowUpRight size={18}/></button><small>Sem cadastro. Sem coleta de dados pessoais.</small>{result && <p className="pro-form-result" role="status" tabIndex={-1} ref={resultRef}>{result}</p>}</form></div></section>
}

export default function ProfessionalDemo({model}) {
  const profile = profiles[model.theme]
  const pageRef=useRef(null)
  usePageMotion(pageRef)
  const [menu,setMenu] = useState(false)
  const [galleryFilter,setGalleryFilter] = useState('Tudo')
  const [modal,setModal] = useState(null)
  const dialog = useRef(null)
  useEffect(() => {if(modal && !dialog.current?.open) dialog.current?.showModal()},[modal])
  useEffect(() => {const escape=event=>{if(event.key==='Escape') setMenu(false)};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[])
  const serviceLabel = {property:'Imóveis',restaurant:'Cardápio',education:'Cursos',fitness:'Modalidades'}[model.theme] || 'Especialidades'
  const nav = [['#experiencia-exclusiva', {dental:'Primeira consulta',law:'Sua demanda',therapy:'Como começar',property:'Seu perfil',architecture:'Materiais',beauty:'Seu estilo',restaurant:'Sua mesa',fitness:'Sua rotina',pet:'Fases da vida',photography:'Coleções',accounting:'Sua empresa',tattoo:'Sua ideia',nutrition:'Sua rotina',barber:'Seu momento',automotive:'Atendimento',education:'Trilhas'}[model.theme]],['#sobre','Sobre'],['#servicos',serviceLabel],['#galeria',['architecture','photography','tattoo'].includes(model.theme) ? 'Portfólio':'Experiência'],['#duvidas','Dúvidas']]
  const about = <section className="pro-about pro-section" id="sobre"><div className="pro-container pro-about-grid"><div className="pro-about-visual"><Image name={profile.aboutPhoto}/><div className="pro-photo-note"><span>01 / NOSSA ESSÊNCIA</span><strong>{model.detail}</strong></div></div><div><span className="pro-kicker">MAIS DO QUE UM SERVIÇO</span><h2>{profile.aboutTitle}</h2><p>{profile.about || model.description + ' ' + model.detail}</p><p>{profile.about2 || 'Acreditamos em relações próximas e em escolhas feitas com intenção. Por isso, dedicamos tempo para conhecer suas referências, alinhar expectativas e cuidar dos detalhes que tornam cada experiência única.'}</p><a className="pro-text-button" href="#jornada">Conheça nosso processo <ArrowRight size={18}/></a></div></div></section>
  const gallery = <section className="pro-gallery pro-section pro-container" id="galeria"><Heading label="UM OLHAR MAIS DE PERTO" text="Explore os ambientes e as referências que traduzem a proposta deste projeto conceitual.">{profile.galleryTitle}</Heading><div className="pro-filters" role="group" aria-label="Filtrar galeria">{['Tudo',...new Set(profile.galleryLabels)].map(label => <button key={label} onClick={()=>setGalleryFilter(label)} aria-pressed={galleryFilter===label}>{label}</button>)}</div><div className="pro-gallery-grid">{profile.gallery.map((name,i)=>({name,i})).filter(({i})=>galleryFilter==='Tudo'||profile.galleryLabels[i]===galleryFilter).map(({name,i})=><button className="pro-gallery-item" key={name} onClick={()=>setModal({title:profile.galleryLabels[i],image:name,text:'Uma referência visual do universo deste projeto. As fotografias são ilustrativas e não representam trabalhos realizados, imóveis disponíveis ou instalações de uma empresa real.'})}><Image name={name}/><span><span><small>0{i+1} / {model.brand}</small><strong>{profile.galleryLabels[i]}</strong></span><ArrowUpRight/></span></button>)}</div></section>
  const services = <section className="pro-services pro-section pro-container" id="servicos"><Heading label={serviceLabel.toUpperCase()} text="Explore as possibilidades e encontre o ponto de partida que faz sentido para você.">{profile.serviceTitle}</Heading><ServiceExplorer model={model} profile={profile} onOpen={setModal}/><aside className="pro-quote-bridge"><p><strong>Imagine seus serviços apresentados assim.</strong>Esta é uma demonstração. Vamos criar uma experiência própria para a sua empresa?</p><a href={whatsapp(`Olá! Gostei da apresentação do modelo ${model.name}. Quero um orçamento para o meu site.`)} target="_blank" rel="noopener noreferrer">Pedir orçamento deste estilo <ArrowUpRight size={17}/></a></aside></section>
  return <div className={`professional-demo pro-${model.theme} layout-${profile.layout}`} id="inicio" ref={pageRef}><ReadingProgress /><a className="skip-link" href="#demo-conteudo">Pular para o conteúdo</a><div className="pro-toolbar"><a href="/#modelos"><ArrowLeft size={16}/><span>Todos os modelos</span></a><span>Demonstração fictícia · {model.profession}</span><a href={whatsapp(`Olá! Gostei do modelo ${model.name} e quero um site assim para meu negócio.`)} target="_blank" rel="noopener noreferrer">Orçar um site assim <ArrowUpRight size={16}/></a></div><header className="pro-header pro-container"><a className="pro-brand" href="#inicio">{model.brand}<span> {model.theme==='dental' ? '✧' : '·'}</span></a><nav aria-label="Navegação do modelo">{nav.map(([href,label])=><a href={href} key={href}>{label}</a>)}</nav><a className="pro-button pro-header-cta" href="#demo-contato">Vamos conversar <ArrowUpRight size={17}/></a><button className="pro-menu-button" aria-label={menu?'Fechar menu':'Abrir menu'} aria-expanded={menu} aria-controls="pro-mobile-nav" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>{menu&&<nav id="pro-mobile-nav" className="pro-mobile-nav" aria-label="Menu do modelo no celular">{[...nav,['#demo-contato','Vamos conversar']].map(([href,label])=><a href={href} key={href} onClick={()=>setMenu(false)}>{label}<ArrowUpRight size={18}/></a>)}</nav>}</header>
    <main id="demo-conteudo"><section className="pro-hero"><div className="pro-container pro-hero-grid"><div className="pro-hero-copy"><span className="pro-kicker">{model.kicker}</span><h1><WordReveal text={model.headline}/></h1><p>{model.description}</p><div className="pro-hero-actions"><a className="pro-button" href="#servicos">{model.cta}<ArrowUpRight size={19}/></a><a className="pro-secondary-link" href="#sobre">Nossa essência <ArrowRight size={17}/></a></div><div className="pro-hero-caption"><span/> {profile.features[0]}</div></div><div className="pro-hero-media"><Image name={model.image} eager/><span className="pro-image-caption">{model.brand}<ArrowUpRight size={24}/></span>{['calm','natural','beauty'].includes(profile.layout)&&<div className="pro-inset-photo"><Image name={profile.aboutPhoto}/></div>}</div></div></section>
    <div className="pro-values"><div className="pro-container">{profile.features.map(item=><span key={item}><Check size={18}/>{item}</span>)}</div></div>
    {sectionOrder[model.theme].map(key=><Fragment key={key}>{({about,gallery,services,signature:<SignatureExperience model={model} Image={Image}/>})[key]}</Fragment>)}
    <section className="pro-feature pro-section"><div className="pro-container"><span className="pro-kicker">O QUE ORIENTA NOSSO TRABALHO</span><h2>{profile.featureTitle}</h2><div className="pro-feature-grid">{profile.features.map((item,i)=><article key={item}><span>0{i+1}</span><h3>{item}</h3><p>{['Tudo começa por uma conversa. Entender o seu contexto nos ajuda a cuidar do que realmente importa.','As escolhas são explicadas com clareza, com espaço para perguntas e respeito às suas expectativas.','Do primeiro encontro aos próximos passos, os detalhes fazem parte de uma experiência próxima.'][i]}</p></article>)}</div></div></section>
    <section className="pro-journey pro-section pro-container" id="jornada"><Heading label="PASSO A PASSO" text="Uma jornada com espaço para você participar, perguntar e acompanhar cada etapa.">{journeys[model.theme][0]}</Heading><div className="pro-steps">{profile.steps.map((title,i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{journeys[model.theme][i+1]}</p></article>)}</div></section>
    <section className="pro-journal pro-section pro-container"><Heading label="PARA CONHECER MELHOR">{profile.articleTitle||'Ideias, referências e boas conversas.'}</Heading><div className="pro-journal-grid">{profile.articles.map((title,i)=><button key={title} onClick={()=>setModal({title,image:profile.gallery[i%profile.gallery.length],text:`${title}. ${i===0?'O primeiro encontro é um momento para compartilhar expectativas e esclarecer dúvidas. Você pode organizar suas referências e pensar no que gostaria de conhecer melhor.':'Cada experiência começa com atenção. Conversar sobre preferências, conhecer as possibilidades e entender as etapas ajuda a construir uma relação mais próxima.'} Aqui, valorizamos a escuta, a clareza e o tempo necessário para alinhar os próximos passos. Este texto faz parte de um site conceitual e não substitui orientação profissional individualizada.`})}><Image name={profile.gallery[i%profile.gallery.length]}/><div><span className="pro-kicker">NOSSO UNIVERSO · LEITURA BREVE</span><h3>{title}</h3><span className="pro-text-button">Ler conteúdo <ArrowUpRight size={18}/></span></div></button>)}</div></section>
    <section className="pro-faq pro-section pro-container" id="duvidas"><div><span className="pro-kicker">PERGUNTAS FREQUENTES</span><h2>Podemos<br/>deixar mais claro.</h2><p>Uma boa conversa também começa com suas perguntas.</p></div><div>{[[profile.question||'Como funciona o primeiro contato?',profile.answer||'O primeiro contato é dedicado a conhecer suas expectativas e apresentar as possibilidades de atendimento. Os detalhes de funcionamento são definidos pela empresa na versão personalizada.'],['Como escolher a melhor opção para mim?','Explore as especialidades e conheça a proposta de cada uma. Na versão final, a equipe responsável ajuda a esclarecer as diferenças e a entender suas prioridades.'],['Onde encontro informações sobre valores e disponibilidade?','Essas informações são fornecidas pelo profissional ou pela empresa após conhecer sua necessidade. Este modelo não apresenta preços, ofertas ou horários reais.'],['Este formulário faz uma reserva de verdade?','Não. O formulário permite experimentar o fluxo de navegação, mas não envia informações nem realiza atendimentos, reservas ou contratações.'],['Gostei deste site. Posso ter um com a minha marca?','Sim. Fale com a Soluções Digitais pelo botão de WhatsApp. Fotos, cores, textos, serviços e funcionalidades podem ser personalizados para o seu negócio.']].map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>
    <Contact model={model} profile={profile}/><section className="pro-conversion pro-container"><div><span className="pro-kicker">SEU NEGÓCIO PODE ESTAR AQUI</span><h2>Seu negócio pode transmitir<br/>essa confiança desde o primeiro clique.</h2><p>Gostou deste caminho? Vamos adaptar a estrutura, a mensagem e a identidade ao seu negócio. Peça uma proposta com escopo, prazo e investimento definidos antes de começar.</p></div><a className="pro-button" href={whatsapp(`Olá! Quero personalizar o modelo ${model.name} para minha empresa.`)} target="_blank" rel="noopener noreferrer">Solicitar meu orçamento <ArrowUpRight size={19}/></a></section>
    <section className="pro-related pro-container"><span className="pro-kicker">OUTROS ESTILOS PARA EXPLORAR</span><div>{models.filter(item=>item.slug!==model.slug).slice(model.theme==='dental'?1:0,model.theme==='dental'?4:3).map(item=><a href={`/modelos/${item.slug}`} key={item.slug}><Image name={item.image}/><span>{item.name}<ArrowUpRight size={18}/></span></a>)}</div></section></main><footer className="pro-footer pro-container"><a className="pro-brand" href="#inicio">{model.brand}</a><p>Marca fictícia · Fotografias ilustrativas<br/>Conceito de site por <a href="/">Soluções Digitais</a><br/>CNPJ da agência: {cnpj}</p><a href="/#modelos">Voltar aos modelos <ArrowUpRight size={17}/></a></footer><WhatsAppButton model={model}/>
    <dialog ref={dialog} className="pro-dialog" aria-labelledby="pro-dialog-title" onKeyDown={event=>{if(event.key==="Escape"){event.preventDefault();dialog.current.close()}}} onClose={()=>setModal(null)} onClick={event=>{if(event.target===event.currentTarget)dialog.current.close()}}>{modal&&<><button className="pro-dialog-close" aria-label="Fechar detalhes" autoFocus onClick={()=>dialog.current.close()}><X/></button>{modal.image&&<Image name={modal.image} eager/>}<div><span className="pro-kicker">{model.brand} · CONTEÚDO ILUSTRATIVO</span><h2 id="pro-dialog-title">{modal.title}</h2><p>{modal.text}</p><button className="pro-button" onClick={()=>dialog.current.close()}>Continuar explorando <ArrowRight size={18}/></button></div></>}</dialog>
  </div>
}
