import { VisualAtmosphere } from './VisualEffects'
import { useState } from 'react'
import { ArrowUpRight, ArrowRight, Check, Plus, Minus, ChevronLeft, ChevronRight, Camera, Heart, Sparkles, Scissors, Wrench, BookOpen, Leaf, ShieldCheck, Smile, MapPin } from 'lucide-react'
import { BreathingOrb } from './Motion'

export const signatures = {
 dental:{label:'SEU PRIMEIRO ENCONTRO',title:'Chegue com perguntas. Saia entendendo os próximos passos.',intro:'Conheça a experiência de uma avaliação, do acolhimento ao planejamento.'},
 law:{label:'UM OLHAR PARA SUA DEMANDA',title:'Sua decisão merece contexto. Sua história merece atenção.',intro:'Escolha um cenário para conhecer nossa forma de organizar uma primeira conversa.'},
 therapy:{label:'UMA PAUSA NO SEU DIA',title:'Você não precisa ter todas as respostas para começar.',intro:'Escolha como gostaria de conhecer a proposta de cuidado.'},
 property:{label:'SEU JEITO DE MORAR',title:'Antes do endereço, vem a vida que você quer viver.',intro:'Monte uma lista de prioridades para explorar seu próximo lar.'},
 architecture:{label:'MATÉRIA, LUZ E INTENÇÃO',title:'O mesmo espaço. Diferentes formas de sentir.',intro:'Explore três direções de materiais para imaginar a atmosfera de um projeto.'},
 beauty:{label:'SEU VISUAL, SUA ASSINATURA',title:'Uma referência inspira. A sua identidade guia.',intro:'Escolha a atmosfera que mais combina com o seu próximo momento.'},
 restaurant:{label:'A MESA É O PONTO DE ENCONTRO',title:'Um jantar a dois. Uma celebração. Uma boa desculpa para reunir.',intro:'Imagine sua próxima visita e conheça a proposta da casa para cada encontro.'},
 fitness:{label:'SUA ROTINA EM MOVIMENTO',title:'O melhor treino começa com um plano que cabe na sua semana.',intro:'Explore uma composição ilustrativa de modalidades para diferentes ritmos.'},
 pet:{label:'CADA FASE PEDE UM OLHAR',title:'Do primeiro passo aos anos de companhia.',intro:'Explore o universo de cuidados que pode fazer parte da história do seu pet.'},
 photography:{label:'UM OLHAR, UMA NARRATIVA',title:'Não é só a imagem. É o que você sente quando olha de novo.',intro:'Entre nas coleções e descubra diferentes maneiras de contar uma história.'},
 accounting:{label:'QUAL É O MOMENTO DA SUA EMPRESA?',title:'A contabilidade precisa acompanhar a sua fase.',intro:'Selecione o seu momento para conhecer uma proposta de organização.'},
 tattoo:{label:'DO CONCEITO AO TRAÇO',title:'Sua próxima tatuagem começa com uma boa ideia.',intro:'Escolha uma direção artística e descubra como construímos a conversa criativa.'},
 nutrition:{label:'A ROTINA TAMBÉM SENTA À MESA',title:'Antes de mudar tudo, vamos entender a sua vida.',intro:'Explore o que pode entrar na conversa com o profissional de nutrição.'},
 barber:{label:'MONTE SEU MOMENTO',title:'Um corte. Um ritual. Um tempo que é seu.',intro:'Selecione o que gostaria de conhecer para visualizar uma experiência no Distrito.'},
 automotive:{label:'VOCÊ ENTENDE ANTES DE AUTORIZAR',title:'Sem adivinhação. Uma conversa clara sobre seu veículo.',intro:'Escolha o motivo do contato para conhecer as etapas do atendimento.'},
 education:{label:'DESCUBRA SUA PRÓXIMA TRILHA',title:'Curiosidade é um ótimo ponto de partida.',intro:'Escolha o que você quer aprender e explore uma sequência de projetos.'}
}
const options = {
 dental:[['Escuta','O que você gostaria de entender sobre seu sorriso?','O encontro começa com suas dúvidas, sua rotina e suas expectativas. Há espaço para conversar com calma, sem precisar chegar com uma decisão pronta.'],['Avaliação','Conhecer antes de propor.','A equipe responsável avalia cada caso e explica as possibilidades. O planejamento depende de uma avaliação individual, nunca de uma promessa genérica.'],['Planejamento','Você participa das escolhas.','Etapas, alternativas e condições são apresentadas com clareza. Você entende o caminho proposto antes de decidir como deseja seguir.']],
 law:[['Para minha empresa','Decisões empresariais com informações organizadas.',['Contexto do negócio','Objetivo da consulta','Documentação pertinente']],['Para minha família','Escuta reservada para um momento importante.',['O que precisa ser esclarecido','Contexto da situação','Próximos passos da conversa']],['Para meu patrimônio','Atenção às relações que envolvem seus bens.',['Natureza da demanda','Dúvidas iniciais','Escopo do atendimento']]],
 therapy:[['Quero entender como funciona','Um primeiro encontro para esclarecer suas dúvidas, conhecer a proposta e perceber como você se sente nessa conversa.'],['Prefiro encontros online','Um formato para conversar à distância, com atenção à privacidade e às condições combinadas com o profissional.'],['Quero conhecer o espaço','Uma oportunidade de entender a experiência presencial e conhecer a proposta de acolhimento.']],
 architecture:[['Natural','Madeira, fibras e luz suave.',['#b9926a','#ded3bd','#616b4b'],'casa'],['Essencial','Linhas puras, texturas e silêncio visual.',['#dad7ce','#88897f','#3c403a'],'sala'],['Urbano','Contrastes, concreto e presença.',['#888784','#333638','#af7b53'],'arquitetura']],
 beauty:[['Natural','Leveza que acompanha seu jeito.','Uma conversa sobre movimento, textura e um visual que faça sentido na sua rotina.'],['Marcante','Presença em cada detalhe.','Referências de contraste e expressão para construir uma direção com personalidade.'],['Especial','Um momento para guardar.','Uma proposta para eventos e celebrações, alinhada às referências e aos detalhes da ocasião.']],
 fitness:[['2 dias','Um começo possível.',['Força','Pausa','Mobilidade','Pausa','Rotina livre']],['3 dias','Equilíbrio na semana.',['Força','Pausa','Condicionamento','Pausa','Mobilidade']],['4 dias','Mais espaço para se movimentar.',['Força','Mobilidade','Pausa','Condicionamento','Força']]],
 pet:[['Filhote','Novidades para eles. Muitas perguntas para você.','Um espaço para conversar sobre adaptação, rotina e acompanhamento com o profissional responsável.'],['Adulto','Cuidado que acompanha a vida em movimento.','Atenção às particularidades do seu companheiro e às dúvidas que aparecem no dia a dia.'],['Sênior','Mais tempo juntos merece atenção aos detalhes.','Uma escuta próxima sobre mudanças na rotina e possibilidades de acompanhamento individual.']],
 photography:[['Histórias a dois','O encontro, a pausa, o que fica.','casamento'],['Retratos','Um jeito de se ver com outros olhos.','retrato'],['Autoral','A beleza também está no caminho.','natureza']],
 accounting:[['Estou começando','Uma base organizada para o próximo passo.',['Entender o modelo de negócio','Mapear documentos e informações','Alinhar o escopo do acompanhamento']],['Quero organizar','Mais clareza sobre o que acontece todo mês.',['Conhecer a rotina atual','Organizar fluxos e responsabilidades','Definir um calendário de acompanhamento']],['Estou crescendo','Processos que acompanham uma nova fase.',['Revisitar necessidades da empresa','Alinhar a troca de informações','Planejar a continuidade do atendimento']]],
 tattoo:[['Fine line','Delicadeza também pode ter presença.','Desenhos que exploram linhas leves, composição e espaço. Compartilhe suas referências para desenvolver uma proposta autoral.'],['Blackwork','Contraste que assume seu lugar.','Uma direção que valoriza áreas de preto, formas e impacto visual. Cada composição começa com a sua ideia.'],['Lettering','Palavras que merecem um desenho só delas.','O ritmo das letras, a intenção da mensagem e a composição orientam uma conversa criativa antes do esboço.']],
 nutrition:[['Meu dia é corrido','Praticidade faz parte da conversa.','Horários, deslocamentos, acesso aos alimentos e preferências ajudam o profissional a entender seu contexto.'],['Quero mais organização','Começar pelo que acontece de verdade.','Uma conversa sobre como sua rotina funciona hoje, sem julgamentos e sem fórmulas iguais para histórias diferentes.'],['Tenho muitas dúvidas','Você não precisa chegar sabendo tudo.','Leve suas perguntas para o encontro. O acompanhamento individual permite esclarecer o que faz sentido para você.']],
 automotive:[['Revisão','Conhecer o histórico vem primeiro.',['Conversa sobre o uso do veículo','Avaliação conforme a necessidade','Orçamento para sua aprovação']],['Percebi algo diferente','Sua observação ajuda a começar.',['Você descreve o que percebeu','A equipe realiza a avaliação','Os serviços são explicados antes da execução']],['Quero um orçamento','Clareza para tomar sua decisão.',['Alinhamento sobre a solicitação','Avaliação técnica quando necessária','Escopo e condições apresentados']]],
 education:[['Idiomas','Da primeira conversa ao mundo de possibilidades.',['Apresente sua história','Explore situações do dia a dia','Construa uma conversa em grupo']],['Tecnologia','Uma ideia na cabeça. Um projeto na tela.',['Conheça as ferramentas','Resolva um desafio prático','Apresente sua criação']],['Criação','Experimente. Misture. Descubra seu jeito.',['Reúna suas referências','Experimente materiais e formatos','Compartilhe seu projeto']]]
}
function Picks({items,value,onChange,label}){return <div className="signature-picks" role="group" aria-label={label}>{items.map((item,i)=><button key={item[0]} aria-pressed={value===i} onClick={()=>onChange(i)}>{item[0]}</button>)}</div>}
function Next({children='Conhecer o atendimento'}){return <a className="pro-button" href="#demo-contato">{children}<ArrowUpRight size={18}/></a>}
export default function SignatureExperience({model,Image}){
 const [active,setActive]=useState(0)
 const [chosen,setChosen]=useState([])
 const [guests,setGuests]=useState(2)
 const meta=signatures[model.theme]
 const data=options[model.theme]
 const toggle=value=>setChosen(items=>items.includes(value)?items.filter(item=>item!==value):[...items,value])
 let content
 switch(model.theme){
 case 'dental':content=<div className="smile-timeline"><div className="smile-steps">{data.map(([label,title,text],i)=><button key={label} aria-pressed={active===i} onClick={()=>setActive(i)}><span>0{i+1}</span><strong>{label}</strong></button>)}</div><div className="signature-stage smile-panel"><Smile size={42}/><span className="signature-counter">0{active+1} / 03</span><h3>{data[active][1]}</h3><p>{data[active][2]}</p><Next>Conhecer a primeira consulta</Next></div></div>;break
 case 'law':content=<div className="law-dossier"><Picks items={data} value={active} onChange={setActive} label="Cenário da consulta"/><div className="signature-stage dossier-paper"><span className="pro-kicker">DOSSIÊ INICIAL / 0{active+1}</span><h3>{data[active][1]}</h3><ul>{data[active][2].map((t,i)=><li key={t}><span>0{i+1}</span>{t}</li>)}</ul><p>Conversa confidencial e análise do contexto, sem antecipar conclusões ou prometer resultados.</p><Next>Conhecer a proposta de atendimento</Next></div></div>;break
 case 'therapy':content=<div className="therapy-pause"><BreathingOrb/><div><Picks items={data} value={active} onChange={setActive} label="Como começar"/><div className="signature-stage"><span className="pro-kicker">NO SEU TEMPO</span><h3>{data[active][0]}</h3><p>{data[active][1]}</p><Next>Dar o primeiro passo</Next></div></div></div>;break
 case 'property':content=<div className="property-wishlist"><div><Image name="casa"/><span className="wish-photo-label">O SEU JEITO DE VIVER VEM PRIMEIRO</span></div><div className="signature-stage"><MapPin size={28}/><h3>O que não pode faltar?</h3><div className="wish-options">{['Mais luz natural','Espaço para a família','Área externa','Praticidade urbana','Um lugar para trabalhar','Ambientes integrados'].map(t=><button key={t} aria-pressed={chosen.includes(t)} onClick={()=>toggle(t)}>{chosen.includes(t)?<Check size={18}/>:<Plus size={18}/>} {t}</button>)}</div><p role="status">{chosen.length ? chosen.length+' prioridades selecionadas. Imagine uma curadoria que começa pelo seu perfil.':'Selecione suas prioridades para começar a imaginar.'}</p><Next>Conversar sobre meu próximo imóvel</Next></div></div>;break
 case 'architecture':content=<div className="material-board"><div className="material-image"><Image name={data[active][3]}/><span>ESTUDO DE ATMOSFERA / 0{active+1}</span></div><div className="signature-stage"><Picks items={data} value={active} onChange={setActive} label="Direção de materiais"/><h3>{data[active][1]}</h3><div className="material-swatches" aria-label="Paleta de materiais">{data[active][2].map(c=><span key={c} style={{background:c}}/>)}</div><p>Uma referência visual, não um projeto executado. Materiais, iluminação e necessidades são estudados em conjunto para chegar a uma proposta própria.</p><Next>Imaginar meu projeto</Next></div></div>;break
 case 'beauty':content=<div className="beauty-editorial"><span className="beauty-word" aria-hidden="true">É sobre<br/><em>você.</em></span><div className="signature-stage"><Picks items={data} value={active} onChange={setActive} label="Atmosfera do visual"/><span className="pro-kicker">MOOD / {data[active][0]}</span><h3>{data[active][1]}</h3><p>{data[active][2]}</p><Next>Conversar sobre meu visual</Next></div><div className="beauty-editorial-photo"><Image name="beleza"/></div></div>;break
 case 'restaurant':content=<div className="restaurant-table"><Image name="restaurante"/><div className="signature-stage table-card"><span className="pro-kicker">O SEU PRÓXIMO ENCONTRO</span><h3>Tem lugar para<br/>uma boa conversa.</h3><div className="guest-control"><button aria-label="Diminuir pessoas" disabled={guests===1} onClick={()=>setGuests(v=>v-1)}><Minus/></button><span aria-live="polite"><strong>{guests}</strong> {guests===1?'pessoa':'pessoas'}</span><button aria-label="Aumentar pessoas" disabled={guests===12} onClick={()=>setGuests(v=>v+1)}><Plus/></button></div><p>{guests<=2?'Uma mesa para desacelerar e aproveitar cada detalhe.':guests<=6?'Uma boa ocasião para compartilhar sabores e histórias.':'Encontros maiores pedem uma conversa sobre espaço e experiência.'}</p><Next>Simular interesse em uma mesa</Next><small>Não consulta disponibilidade nem realiza reserva.</small></div></div>;break
 case 'fitness':content=<div className="fitness-planner"><div><span className="fitness-number" aria-hidden="true">{active+2}<small>DIAS / SEMANA</small></span><Picks items={data} value={active} onChange={setActive} label="Ritmo da semana"/></div><div className="signature-stage"><h3>{data[active][1]}</h3><div className="week-grid">{data[active][2].map((t,i)=><div key={i}><span>{['SEG','TER','QUA','QUI','SEX'][i]}</span><strong>{t}</strong></div>)}</div><p>Composição apenas demonstrativa. O treino real depende da avaliação e da orientação de um profissional habilitado.</p><Next>Conhecer as modalidades</Next></div></div>;break
 case 'pet':content=<div className="pet-life"><div className="pet-life-photo"><Image name="pet"/><Heart size={55}/></div><div><Picks items={data} value={active} onChange={setActive} label="Fase do pet"/><div className="signature-stage"><span className="pro-kicker">A VIDA COM ELES</span><h3>{data[active][1]}</h3><p>{data[active][2]}</p><Next>Conhecer o cuidado para meu pet</Next></div></div></div>;break
 case 'photography':content=<div className="photo-story"><div className="photo-story-image"><Image name={data[active][2]}/><span>COLEÇÃO CONCEITUAL / 0{active+1}</span></div><div className="signature-stage photo-story-caption"><Camera size={27}/><h3>{data[active][0]}</h3><p>{data[active][1]}</p><div className="story-controls"><button aria-label="Coleção anterior" onClick={()=>setActive(v=>(v+2)%3)}><ChevronLeft/></button><span aria-live="polite">0{active+1} / 03</span><button aria-label="Próxima coleção" onClick={()=>setActive(v=>(v+1)%3)}><ChevronRight/></button></div><Next>Quero contar minha história</Next></div></div>;break
 case 'accounting':content=<div className="business-path"><Picks items={data} value={active} onChange={setActive} label="Momento da empresa"/><div className="signature-stage"><span className="pro-kicker">PLANO DE CONVERSA</span><h3>{data[active][1]}</h3><div className="business-checklist">{data[active][2].map((t,i)=><div key={t}><Check size={20}/><span>ETAPA 0{i+1}</span><strong>{t}</strong></div>)}</div><Next>Conversar sobre minha empresa</Next></div></div>;break
 case 'tattoo':content=<div className="tattoo-concept"><div className={'tattoo-type tattoo-type-'+active} aria-hidden="true">{['TRACE.','BLACK.','WORDS.'][active]}<span>IDEIA → DESENHO → IDENTIDADE</span></div><div className="signature-stage"><Picks items={data} value={active} onChange={setActive} label="Direção artística"/><h3>{data[active][1]}</h3><p>{data[active][2]}</p><Next>Conversar sobre minha ideia</Next></div></div>;break
 case 'nutrition':content=<div className="nutrition-routine"><div className="nutrition-collage"><Image name="salada"/><Image name="nutricao"/><span><Leaf size={30}/> Vida real.<br/>Cuidado possível.</span></div><div className="signature-stage"><Picks items={data} value={active} onChange={setActive} label="Conversa sobre a rotina"/><h3>{data[active][1]}</h3><p>{data[active][2]}</p><Next>Conhecer o acompanhamento</Next></div></div>;break
 case 'barber':content=<div className="barber-ticket"><div><Scissors size={36}/><span className="pro-kicker">ESCOLHA SUA EXPERIÊNCIA</span><h3>Seu estilo merece<br/>atenção aos detalhes.</h3><div className="barber-services">{['Corte','Barba','Acabamento','Consultoria de estilo'].map((t,i)=><button aria-pressed={chosen.includes(t)} onClick={()=>toggle(t)} key={t}><span>0{i+1}</span>{t}{chosen.includes(t)?<Check/>:<Plus/>}</button>)}</div></div><div className="signature-stage ticket"><span>DISTRITO 62 / SEU MOMENTO</span><h3>Um tempo<br/>bem aproveitado.</h3><div role="status">{chosen.length?chosen.map(t=><p key={t}>{t}<Check size={16}/></p>):<p>Escolha ao lado o que gostaria de conhecer.</p>}</div><Next>Simular meu atendimento</Next><small>Seleção ilustrativa, sem reserva ou cobrança.</small></div></div>;break
 case 'automotive':content=<div className="auto-diagnostic"><div><Wrench size={45}/><Picks items={data} value={active} onChange={setActive} label="Motivo do contato"/></div><div className="signature-stage"><span className="pro-kicker">PROTOCOLO DE ATENDIMENTO / 0{active+1}</span><h3>{data[active][1]}</h3>{data[active][2].map((t,i)=><div className="diagnostic-step" key={t}><span>0{i+1}</span><strong>{t}</strong><ArrowRight size={18}/></div>)}<p>Este exemplo não realiza diagnóstico. A avaliação do veículo é feita pela equipe responsável.</p><Next>Conversar sobre meu veículo</Next></div></div>;break
 case 'education':content=<div className="learning-map"><Picks items={data} value={active} onChange={setActive} label="Trilha de aprendizagem"/><div className="signature-stage"><BookOpen size={38}/><h3>{data[active][1]}</h3><div className="learning-nodes">{data[active][2].map((t,i)=><article key={t}><span>{i+1}</span><h4>{t}</h4><small>{['EXPLORAR','EXPERIMENTAR','COMPARTILHAR'][i]}</small></article>)}</div><Next>Conhecer essa trilha</Next></div></div>;break
 }
 return <section className={'signature-section signature-'+model.theme+' pro-section'} id="experiencia-exclusiva"><VisualAtmosphere theme={model.theme}/><div className="pro-container"><div className="signature-heading"><span className="pro-kicker">{meta.label}</span><h2>{meta.title}</h2><p>{meta.intro}</p></div>{content}<p className="signature-disclaimer">Experiência demonstrativa · Personalizável para a sua marca</p></div></section>
}

